name: 'Create Pull Request'
description: 'Create a pull request from local changes.'
inputs:
  github-token:
    required: true
    description: >-
      The GitHub token required to perform actions such as pushing commits and
      creating pull requests.
  base-branch:
    required: false
    description: >-
      The name of the base branch to compare changes against. If not specified,
      the default branch will be used.
  branch-name:
    required: true
    description: >-
      The name of the new branch to be created by this action.
  commit-message:
    required: true
    description: >-
      The commit message for the new commit created by this action.
  title:
    required: true
    description: >-
      The title of the pull request that will be created.
  body:
    required: false
    description: >-
      The body content of the pull request. This can provide additional
      information or context for the changes being made.
runs:
  using: 'node16'
  main: 'dist/index.js'
