name: 'Create Pull Request'
description: 'Create a pull request from local changes.'
inputs:
  github-token:
    required: true
    description: >-
      The GitHub token required to perform actions such as pushing commits and
      creating pull requests.
  base:
    required: false
    description: >-
      The base branch to create the pull request against. Defaults to the
      current `github.ref` context if not set. The git reference for the
      base must exists locally (i.e. "fetched").
  branch-name:
    required: true
    description: >-
      The name of the new branch to be created by this action.
  commit-message:
    required: true
    description: >-
      The commit message for the new commit created by this action.
  title:
    required: true
    description: >-
      The title of the pull request that will be created.
  body:
    required: false
    description: >-
      The body content of the pull request. This can provide additional
      information or context for the changes being made.
  upsert:
    required: false
    default: "false"
    description: >-
      When enabled, updates the existing branch and pull request instead of
      failing.
  ignore-no-changes:
    required: false
    default: "false"
    description: >-
      When enabled, the action will ignore the absence of local changes
      and exit without raising an error.
  auto-merge:
    required: false
    default: "false"
    description: >-
      When enabled, the action will enable auto-merge using the squash merge
      method for the pull request and delete the branch after merge.
  repository:
    required: false
    description: >-
      The repository to create the branch and pull request on, for example
      `canonical/create-pull-request`. Defaults to the current repository if
      not set.

runs:
  using: 'node20'
  main: 'dist/index.js'
